spring:
  application:
    name: shipment-transportation

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shipment_db
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

  cloud:
    function:
      definition: packagePacked
    stream:
      bindings:
        packagePacked-in-0:
          destination: fulfillment.warehouse.v1.events
          group: shipment-group
        shipmentDispatched-out:
          destination: fulfillment.shipment.v1.events
        shipmentDelivered-out:
          destination: fulfillment.shipment.v1.events

  main:
    banner-mode: off

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${OTEL_TRACES_SAMPLING_RATE:1.0}
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
    metrics:
      export:
        enabled: true
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
        step: 10s
        resource-attributes:
          service.name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

shipment:
  events:
    dispatched:
      type: com.paklog.shipment.dispatched.v1
      topic: fulfillment.shipment.v1.events
    delivered:
      type: com.paklog.shipment.delivered.v1
      topic: fulfillment.shipment.v1.events

outbox:
  max-attempts: 5
  publisher:
    interval: 30000

---
# Docker profile configuration
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: shipment_db

  kafka:
    bootstrap-servers: kafka:9092

---
# Test profile configuration
spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shipment_test_db

  kafka:
    bootstrap-servers: localhost:9092
